<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;

class CountCommand extends Command
{
        protected function configure()
        {
            $this->setName('ask:numbers')
                ->setDescription(
                    'Komenda asks for two numbers and then calculates the result of one of the basic math operations:
                               addition, subtraction, multiplication and division.'
                )
                ->setHelp('Enter two numbers and then enter the sign of the math operation: (+, -, *, /)');


            parent::configure(); // TODO: Change the autogenerated stub
        }

        protected function execute(InputInterface $input, OutputInterface $output)
        {
            $helper = $this->getHelper('question');

            $fNumber = $helper->ask($input, $output, new Question(
                "Enter first number: ", 0
            ));
            $sNumber = $helper->ask($input, $output, new Question(
                "Enter second number: ", 0
            ));

//            bscale(3);


            $output->writeln('<question>' . $fNumber. '<question>');
            $output->writeln('<question>' . $sNumber. '<question>');
            return Command::SUCCESS;
        }
}
